### ISSUE TITLE
Add all doc files

### ISSUE THREAD

**Issue by Indigo744** [neveldo/mapael-documentation#2]
Missing files are:
- ["SVG to Mapael" tool](http://www.vincentbroute.fr/mapael/svg-to-mapael.php)
- ["Mapael to SVG" tool](http://www.vincentbroute.fr/mapael/mapael-to-svg.php)
- [getCoords() generator](http://www.vincentbroute.fr/mapael/getcoords.php)

**Comment by neveldo** [comment]
Yes, and there are also some missing images, JS and CSS files. I will do some cleanings on these files before open-sourcing, they should be added asap !

**Comment by neveldo** [comment]
Here we go ! :)
